Add user bin

diff --git a/setup_macOS b/setup_macOS
--- a/setup_macOS
+++ b/setup_macOS
@@ -189,6 +189,20 @@ p_header "Install Vim plugins via Vundle"
 vim +PluginInstall +qall > /dev/null || { echo "Failed" >&2;exit 1; }
 p_success "Done"
 
+
+# ----------------------------------------------------
+# Personal scripts
+
+p_header "Copy personal scripts to user home bin"
+if [[ ! -d "${HOME}/bin" ]]; then
+    mkdir "${HOME}/bin" || { echo "Failed" >&2;exit 1; }
+fi
+# -n for do not overwriting
+# -v for verbose
+cp -vn bin/* "${HOME}/bin" || exitcode=1
+p_success "Done"
+
+
 # ----------------------------------------------------
 # macOS System Preferences
 
